'use strict';

const path = require('path');
const { PreMergeValidator, CHECK_STATUS } = require('./pre-merge-validator');
const { ReleaseNotesGenerator } = require('./release-notes');

/**
 * CI Runner
 *
 * Entry point for running GYWD checks in CI/CD pipelines.
 * Can be invoked directly: node lib/ci/ci-runner.js [command] [options]
 *
 * Commands:
 *   validate       Run pre-merge validation checks
 *   release-notes  Generate release notes from GYWD data
 *   report         Generate a full CI report (validate + summary)
 */
class CIRunner {
  constructor(options = {}) {
    this.projectRoot = options.projectRoot || process.cwd();
    this.planningDir = options.planningDir || path.join(this.projectRoot, '.planning');
    this.outputFormat = options.outputFormat || 'text'; // text, json, markdown
    this.strict = options.strict || false;
  }

  /**
   * Run pre-merge validation
   * @param {object} options
   * @returns {object} Validation report
   */
  runValidation(options = {}) {
    const validator = new PreMergeValidator({
      projectRoot: this.projectRoot,
      planningDir: this.planningDir,
      strict: this.strict,
    });

    const report = validator.validate(options);
    return {
      command: 'validate',
      report,
      formatted: validator.formatReport(report),
    };
  }

  /**
   * Generate release notes
   * @param {object} options
   * @returns {object} Release notes
   */
  generateReleaseNotes(options = {}) {
    const generator = new ReleaseNotesGenerator({
      projectRoot: this.projectRoot,
      planningDir: this.planningDir,
    });

    const notes = generator.generate(options);
    return {
      command: 'release-notes',
      ...notes,
    };
  }

  /**
   * Generate full CI report (validation + release notes summary)
   * @param {object} options
   * @returns {object} Full report
   */
  generateReport(options = {}) {
    const validation = this.runValidation(options);
    const notes = this.generateReleaseNotes(options);

    return {
      command: 'report',
      validation: validation.report,
      releaseNotes: notes.data,
      summary: {
        validationPassed: validation.report.passed,
        checksRun: validation.report.summary.total,
        checksFailed: validation.report.summary.failed,
        phasesCompleted: notes.data.phases.length,
        decisionsRecorded: notes.data.decisions.length,
        version: notes.data.version,
      },
      formatted: this._formatFullReport(validation, notes),
    };
  }

  /**
   * Format full report as markdown
   */
  _formatFullReport(validation, notes) {
    const lines = ['# GYWD CI Report', ''];

    // Validation summary
    lines.push('## Pre-Merge Validation');
    lines.push('');
    lines.push(validation.report.passed ? '**Status: PASSED** ✅' : '**Status: FAILED** ❌');
    lines.push('');

    const icon = {
      [CHECK_STATUS.PASSED]: '✅',
      [CHECK_STATUS.FAILED]: '❌',
      [CHECK_STATUS.WARNING]: '⚠️',
      [CHECK_STATUS.SKIPPED]: '⏭️',
    };

    for (const result of validation.report.results) {
      lines.push(`${icon[result.status] || '?'} ${result.name}: ${result.message}`);
    }
    lines.push('');

    // Release info summary
    lines.push('## Release Summary');
    lines.push('');
    lines.push(`- **Version:** ${notes.data.version}`);
    lines.push(`- **Phases:** ${notes.data.phases.length} completed`);
    lines.push(`- **Decisions:** ${notes.data.decisions.length} recorded`);
    lines.push('');

    lines.push('---');
    lines.push('*Generated by GYWD CI Runner*');

    return lines.join('\n');
  }

  /**
   * Format output based on outputFormat setting
   * @param {object} result
   * @returns {string}
   */
  formatOutput(result) {
    switch (this.outputFormat) {
      case 'json':
        return JSON.stringify(result, null, 2);
      case 'markdown':
        return result.formatted || JSON.stringify(result, null, 2);
      case 'text':
      default:
        return result.formatted || JSON.stringify(result, null, 2);
    }
  }

  /**
   * Parse CLI arguments and run
   * @param {string[]} args - CLI arguments
   * @returns {object} Result
   */
  static run(args = []) {
    const command = args[0] || 'validate';
    const options = {};

    // Parse flags
    for (let i = 1; i < args.length; i++) {
      const arg = args[i];
      if (arg === '--strict') options.strict = true;
      else if (arg === '--json') options.outputFormat = 'json';
      else if (arg === '--markdown') options.outputFormat = 'markdown';
      else if (arg === '--version' && args[i + 1]) {
        options.version = args[++i];
      } else if (arg === '--project' && args[i + 1]) {
        options.projectRoot = args[++i];
      } else if (arg === '--only' && args[i + 1]) {
        options.only = args[++i].split(',');
      } else if (arg === '--skip' && args[i + 1]) {
        options.skip = args[++i].split(',');
      }
    }

    const runner = new CIRunner({
      projectRoot: options.projectRoot,
      outputFormat: options.outputFormat,
      strict: options.strict,
    });

    switch (command) {
      case 'validate':
        return runner.runValidation(options);
      case 'release-notes':
        return runner.generateReleaseNotes(options);
      case 'report':
        return runner.generateReport(options);
      default:
        return { error: `Unknown command: ${command}. Use: validate, release-notes, report` };
    }
  }
}

// CLI entry point
if (require.main === module) {
  const result = CIRunner.run(process.argv.slice(2));
  const runner = new CIRunner({
    outputFormat: process.argv.includes('--json') ? 'json' : 'text',
  });
  const output = runner.formatOutput(result);
  process.stdout.write(output + '\n');

  // Exit with non-zero if validation failed
  if (result.report && !result.report.passed) {
    process.exit(1);
  }
  if (result.validation && !result.validation.passed) {
    process.exit(1);
  }
}

module.exports = {
  CIRunner,
};
